spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

fileUploadFolder: /Users/Andrea/Downloads/DevelHope/SpringBoot/Image